CREATE TABLE products (
	category varchar(250),
	subcategory varchar(250),
	name text,
	current_price decimal,
	raw_price decimal,
	currency varchar(10),
	discount integer,
	likes_count integer,
	is_new boolean,
	brand varchar(250),
	brand_url text,
	codcountry text,
	variation_0_color varchar(100),
	variation_1_color varchar(100),
	variation_0_thumbnail text,
	variation_0_image text,
	variation_1_thumbnail text,
	variation_1_image text,
	image_url text,
	url text,
	id integer,
	model varchar(100)
);